spring.application.name=hackathon
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# https://linkeverything.github.io/springboot/spring-context-path/
server.port=8088
server.servlet.context-path=/hackathon
# Session timeout. If a duration suffix is not specified, seconds will be used.
server.servlet.session.timeout=3600
